<a href="https://colab.research.google.com/github/JeanPablo-007/AnaliticaLab/blob/master/Analitica_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [13]:
#crear el vector con los números 1, 2, 3, 4, 5
vector = np.array([1, 2, 3, 4, 5])
#Se imprime el vector
print(vector)
#Se imprime la forma del vector
print("forma del vector:", vector.shape)
#Se imprimen los datos del vector
print("Tipo de datos del vector: ", vector.dtype)
#Se imprime el tipo del vector
print("tipo del vector: ", type(vector))



[1 2 3 4 5]
forma del vector: (5,)
Tipo de datos del vector:  int64
tipo del vector:  <class 'numpy.ndarray'>


In [12]:
#Se accede a los elementos 2 y 3 dentro dle vector
print("Elementos 2 y 3 del vector: ", vector[1:3])
#Se accede al último elemento del vector
print("ultimo elemento del vector: ", vector[-1])
#Se imprimen los últimos 2 elementos del vector
print("Ultimos 2 elementos del vector", vector[-2:])

Elementos 2 y 3 del vector:  [2 3]
ultimo elemento del vector:  5
Ultimos 2 elementos del vector [4 5]


In [17]:
#Se crea un array de 2 dimensiones
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
#Se imprime el array
print(arr)
#Se imprime la forma del array
print("forma del array:", arr.shape)
#Se imprimen los datos del array
print("Tipo de datos del array: ", arr.dtype)
#Se imprime el tipo del array
print("tipo del array: ", type(arr))


[[1 2 3 4]
 [5 6 7 8]]
forma del array: (2, 4)
Tipo de datos del array:  int64
tipo del array:  <class 'numpy.ndarray'>


In [31]:
#Se accede a los elementos 2 y 3 dentro del array
print("Elementos 2 y 3 del array: ", arr[0, 1:3])
#Se accede al último elemento del array
print("ultimo elemento del array: ", arr[1, -1])
#Se imprimen los últimos 2 elementos del array
print("Ultimos 2 elementos del array", arr[1,-2:])

Elementos 2 y 3 del array:  [2 3]
ultimo elemento del array:  8
Ultimos 2 elementos del array [7 8]
