<a href="https://colab.research.google.com/github/JeanPablo-007/AnaliticaLab/blob/master/Analitica_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#crear el vector con los números 1, 2, 3, 4, 5

In [36]:
vector = np.array([1, 2, 3, 4, 5])

#Se imprime el vector

In [35]:
print(vector)

[1 2 3 4 5]


#Se imprime la forma del vector

In [34]:
print("forma del vector:", vector.shape)

forma del vector: (5,)


#Se imprimen los datos del vector

In [33]:
print("Tipo de datos del vector: ", vector.dtype)

Tipo de datos del vector:  int64


#Se imprime el tipo del vector

In [37]:
print("tipo del vector: ", type(vector))

tipo del vector:  <class 'numpy.ndarray'>


#Se accede a los elementos 2 y 3 dentro dle vector

In [38]:
print("Elementos 2 y 3 del vector: ", vector[1:3])

Elementos 2 y 3 del vector:  [2 3]


#Se accede al último elemento del vector

In [39]:
print("ultimo elemento del vector: ", vector[-1])

ultimo elemento del vector:  5


#Se imprimen los últimos 2 elementos del vector

In [40]:
print("Ultimos 2 elementos del vector", vector[-2:])

Ultimos 2 elementos del vector [4 5]


#Se crea un array de 2 dimensiones

In [46]:

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

#Se imprime el array

In [42]:
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


#Se imprime la forma del array

In [41]:
print("forma del array:", arr.shape)

forma del array: (2, 4)


#Se imprimen los datos del array

In [43]:
print("Tipo de datos del array: ", arr.dtype)

Tipo de datos del array:  int64


#Se imprime el tipo del array

In [47]:
print("tipo del array: ", type(arr))

tipo del array:  <class 'numpy.ndarray'>


#Se accede a los elementos 2 y 3 dentro del array

In [49]:
print("Elementos 2 y 3 del array: ", arr[0, 1:3])

Elementos 2 y 3 del array:  [2 3]


#Se accede al último elemento del array

In [48]:
print("ultimo elemento del array: ", arr[1, -1])

ultimo elemento del array:  8


#Se imprimen los últimos 2 elementos del array

In [50]:
print("Ultimos 2 elementos del array", arr[1,-2:])

Ultimos 2 elementos del array [7 8]
